name: Lint Repo

on:
  push:

jobs:
  lintpython:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"

  lintmarkdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: markdownlint
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: ".github/config/markdownlint.yml"
