name: Lint Code Base

on:
  push:

jobs:
  linting:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
