name: Lint Markdown

on:
  push:

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: markdownlint
      uses: nosborn/github-action-markdown-cli@v1
      with:
        files: .
